apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: h3llra1s3r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        iam.gke.io/gcp-service-account: order-pubsub-sa@linear-pointer-479410-n7.iam.gserviceaccount.com
    spec:
      serviceAccountName: order-sa
      automountServiceAccountToken: true
      containers:
        - name: order-service
          image: mmihov11/order-service:2.0
          ports:
            - containerPort: 8080

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            # -----------------------------
            # Database credentials
            # -----------------------------
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: h3llra1s3r-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: h3llra1s3r-secrets
                  key: POSTGRES_PASSWORD

            # ORDER DB connection (currently not used by your code, but keeping it)
            - name: ConnectionStrings__Orders
              valueFrom:
                secretKeyRef:
                  name: h3llra1s3r-secrets
                  key: ORDER_CONNECTION

            # -----------------------------
            # JWT signing key
            # -----------------------------
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: h3llra1s3r-secrets
                  key: jwt-key

            # -----------------------------
            # GCP Pub/Sub (SAGA)
            # -----------------------------
            - name: Gcp__ProjectId
              value: "linear-pointer-479410-n7"

            - name: Gcp__OrderTopic
              value: "orders-topic"

            - name: Gcp__StockSubscription
              value: "stock-events-sub"

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: h3llra1s3r
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - port: 8080
      targetPort: 8080
