apiVersion: v1
kind: Secret
metadata:
  name: h3llra1s3r-secrets
  namespace: h3llra1s3r
type: Opaque
stringData:
  POSTGRES_USER: h3user
  POSTGRES_PASSWORD: h3pass

  # Catalog DB
  CATALOG_CONNECTION: >
    Host=postgres-catalog.h3llra1s3r.svc.cluster.local;
    Port=5432;
    Database=catalogdb;
    Username=h3user;
    Password=h3pass;
    Pooling=true;

  # Design DB
  DESIGN_CONNECTION: >
    Host=postgres-design.h3llra1s3r.svc.cluster.local;
    Port=5432;
    Database=designdb;
    Username=h3user;
    Password=h3pass;
    Pooling=true;

  # Order DB
  ORDER_CONNECTION: >
    Host=postgres-orders.h3llra1s3r.svc.cluster.local;
    Port=5432;
    Database=orderdb;
    Username=h3user;
    Password=h3pass;
    Pooling=true;

  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin123
