apiVersion: batch/v1
kind: Job
metadata:
  name: k6-jwt-loadtest
  namespace: h3llra1s3r
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:0.54.0
          args:
            - run
            - /scripts/k6-jwt-loadtest.js
          env:
            - name: TARGET_URL
              value: "http://catalog-service:8080"
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
      volumes:
        - name: k6-scripts
          configMap:
            name: k6-jwt-script
