apiVersion: v1
kind: Service
metadata:
  name: postgres-design
  namespace: h3llra1s3r
spec:
  selector:
    app: postgres-design
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-design
  namespace: h3llra1s3r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-design
  template:
    metadata:
      labels:
        app: postgres-design
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "designdb"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: h3llra1s3r-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: h3llra1s3r-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
