apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: h3llra1s3r
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus.h3llra1s3r.svc.cluster.local:9090']

      - job_name: 'catalog-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['catalog-service.h3llra1s3r.svc.cluster.local:8080']

      - job_name: 'design-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['design-service.h3llra1s3r.svc.cluster.local:8080']

      - job_name: 'order-service'
        metrics_path: /metrics
        static_configs:
          - targets: ['order-service.h3llra1s3r.svc.cluster.local:8080']
