apiVersion: v1
kind: Secret
metadata:
  name: h3llra1s3r-secrets
  namespace: h3llra1s3r
type: Opaque
data:
  POSTGRES_USER: bXl1c2Vy        # base64("myuser")
  POSTGRES_PASSWORD: c2VjdXJlcGFzcw==   # base64("securepass")
  POSTGRES_DB: ZGF0YWJhc2U=      # base64("database")
  JWT_SIGNING_KEY: c3VwZXJzZWNyZXRrZXk=  # base64("supersecretkey123")
  CATALOG_CONNECTION: cG9zdGdyZXM6Ly9teXVzZXI6c2VjdXJlcGFzc0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZGF0YWJhc2U=
  ORDER_CONNECTION: cG9zdGdyZXM6Ly9teXVzZXI6c2VjdXJlcGFzc0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZGF0YWJhc2U=
  DESIGN_CONNECTION: cG9zdGdyZXM6Ly9teXVzZXI6c2VjdXJlcGFzc0Bwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvZGF0YWJhc2U=
