apiVersion: apps/v1
kind: Deployment
metadata:
  name: design-service
  namespace: h3llra1s3r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: design-service
  template:
    metadata:
      labels:
        app: design-service
    spec:
      containers:
        - name: design-service
          image: mmihov11/design-service:1.1
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: h3llra1s3r-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: h3llra1s3r-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: design-service
  namespace: h3llra1s3r
spec:
  type: ClusterIP
  selector:
    app: design-service
  ports:
    - port: 8080
      targetPort: 8080
