apiVersion: apps/v1
kind: Deployment
metadata:
  name: design-service
  namespace: h3llra1s3r
spec:
  replicas: 1
  selector:
    matchLabels:
      app: design-service
  template:
    metadata:
      labels:
        app: design-service
    spec:
      containers:
        - name: design-service
          image: mmihov11/design-service:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__Designs
              valueFrom:
                secretKeyRef:
                  name: h3llra1s3r-secrets
                  key: DESIGN_CONNECTION
          livenessProbe:
            httpGet:
              path: /healthz/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: design-service
  namespace: h3llra1s3r
spec:
  type: ClusterIP
  selector:
    app: design-service
  ports:
    - port: 8080
      targetPort: 8080
