apiVersion: v1
kind: Secret
metadata:
  name: h3llra1s3r-secrets
  namespace: h3llra1s3r
type: Opaque
data:
  POSTGRES_USER: aDN1c2Vy
  POSTGRES_PASSWORD: aDNwYXNz
  POSTGRES_DB: aDNkYg==

  CATALOG_CONNECTION: SG9zdD1wb3N0Z3Jlcy5oM2xscmExczNyLnN2Yy5jbHVzdGVyLmxvY2FsO1BvcnQ9NTQzMjtEYXRhYmFzZT1oM2RiO1VzZXJuYW1lPWgzdXNlcjpwYXNzd29yZD1oM3Bhc3M7UG9vbGluZz10cnVlOw==
  ORDER_CONNECTION: SG9zdD1wb3N0Z3Jlcy5oM2xscmExczNyLnN2Yy5jbHVzdGVyLmxvY2FsO1BvcnQ9NTQzMjtEYXRhYmFzZT1oM2RiO1VzZXJuYW1lPWgzdXNlcjpwYXNzd29yZD1oM3Bhc3M7UG9vbGluZz10cnVlOw==
  DESIGN_CONNECTION: SG9zdD1wb3N0Z3Jlcy5oM2xscmExczNyLnN2Yy5jbHVzdGVyLmxvY2FsO1BvcnQ9NTQzMjtEYXRhYmFzZT1oM2RiO1VzZXJuYW1lPWgzdXNlcjpwYXNzd29yZD1oM3Bhc3M7UG9vbGluZz10cnVlOw==
