apiVersion: v1
kind: Secret
metadata:
  name: h3llra1s3r-secrets
  namespace: h3llra1s3r
type: Opaque
stringData:
  POSTGRES_USER: h3user
  POSTGRES_PASSWORD: h3pass
  POSTGRES_DB: h3db

  CATALOG_CONNECTION: >
    Host=postgres.h3llra1s3r.svc.cluster.local;Port=5432;Database=h3db;
    Username=h3user;Password=h3pass;Pooling=true;

  DESIGN_CONNECTION: >
    Host=postgres.h3llra1s3r.svc.cluster.local;Port=5432;Database=h3db;
    Username=h3user;Password=h3pass;Pooling=true;

  ORDER_CONNECTION: >
    Host=postgres.h3llra1s3r.svc.cluster.local;Port=5432;Database=h3db;
    Username=h3user;Password=h3pass;Pooling=true;

  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin123
