apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-sa
  namespace: h3llra1s3r
  annotations:
    iam.gke.io/gcp-service-account: order-pubsub-sa@linear-pointer-479410-n7.iam.gserviceaccount.com
