groups:
  - name: service-alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 * (1 - avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[2m]))) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% for more than 2 minutes."
