apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: h3llra1s3r
subjects:
  - kind: ServiceAccount
    name: readonly-sa
    namespace: h3llra1s3r
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io
