apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: h3llra1s3r-order
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mishoka11/Project--H3lra1s3r'
    targetRevision: main
    path: k8s/order
  destination:
    server: https://kubernetes.default.svc
    namespace: h3llra1s3r

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
